global using System;
global using System.IO;
global using System.Text;
global using System.Diagnostics;
global using System.Collections.Generic;
global using System.Linq;
global using BootCamp;
global using BootCamp.Libs;
global using Demo_Recursion;
global using Env = System.Environment;
global using static System.Console;
global using System.Runtime.InteropServices;
