global using System;
global using System.IO;
global using System.Text;
global using System.Diagnostics;
global using System.Collections.Generic;
global using System.Linq;
global using BootCamp;
global using static System.Console;
global using System.Runtime.InteropServices;
global using System.Reflection;
global using BootCamp.Attrs;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Configuration;
